server:
  port: 8080

spring:
  application:
    name: apollo
  h2:
    console:
      enabled: true
      path: /sekhmet-db 
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      
management:
  endpoint:
    health:
      enabled: true
    mappings:
      enabled: true